config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'game#index', as: 'index'
  get '/play', to: 'game#new_game', as: 'new_game'
  get '/play/:uuid', to: 'game#play', as: 'play'
  post '/play/:uuid', to: 'game#guess', as: 'guess'

  root "game#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :word
  has_many :guesses

  MAX_GUESSES = 6

  def add_guess(guess)
    if self.ended?
      fail("Game has ended")
    end

    self.guesses.create(attempt: guess, feedback: GameService::judge_guess(self, guess))
  end

  def guesses_left
    MAX_GUESSES - self.guesses.count
  end

  def ended?
    self.guesses_left < 1 || self.won?
  end

  def won?
    !self.guesses.find_by_attempt(self.word.word).nil?
  end
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :game
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end

  def new_game
    game = GameService::new_game
    redirect_to action: 'play', uuid: game.uuid
  end

  def play
    @game = Game.find_by_uuid(params[:uuid])
  end

  def guess
    game = Game.find_by_uuid(params[:uuid])
    guess = params[:guess]

    guess_validation = GuessService::validate_guess(guess)
    if guess_validation[:status] == 'success'
      game.add_guess(guess)
    else
      flash[:error] = guess_validation[:message]
    end

    redirect_to action: 'play', uuid: game.uuid
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/index.html.erb
<h1>Wordle</h1>

<a href="<%= new_game_url %>">Play Wordle</a>

app/views/game/play.html.erb
<div class="row mt-3">
  <h1 class="text-center">Wordle</h1>
</div>

<% if flash[:error] %>
  <div id="flash-message" class="col-6 offset-3 alert alert-danger">
    Error: <%= flash[:error] %>
  </div>
<% end %>

<div class="col-6 offset-3">
  <div id="word-field" class="row gx-2">
    <% @game.guesses.each do |guess| %>
      <div class="col-1"></div>
        <% guess.attempt.split('').each_with_index do |letter, index|
          letter_feedback = guess.feedback.split('')[index]
          background_color = case letter_feedback
            when '0' then 'bg-secondary text--white'
            when '1' then 'bg-success text-white'
            when '2' then 'bg-warning text-black'
            end
        %>
        <div id="letter-wrap" class="col-2 py-1">
          <div id="letter" class="<%= background_color %>">
            <%= letter %>
          </div>
        </div>
      <% end %>
      <div class="col-1"></div>
    <% end %>
  </div>
</div>

<% if @game.ended? %>
  <% if @game.won? %>
    <div id="winner">
      You won!!
    </div>
  <% else %>
    <div id="game-over">
      Game Over! The answer was: <b><%= @game.word.word %></b>
    </div>
  <% end %>
  <div class="text-center pt-3">
    <a href="<%= new_game_url %>" class="btn btn-primary">Play again!</a>
  </div>
<% else %>
  <div id="guesses-left" class="col-6 offset-3 text-end">
    You have <%= @game.guesses_left %> guess<% if @game.guesses_left > 1 %>es<%end %> left.
  </div>

  <div id="guess-form" class="row">
    <div class="col-6 offset-3">
      <%= form_with url: "/play/#{@game.uuid}", method: :post, html: { autocomplete: 'off' } do |form| %>
        <%= form.label :guess, "Your next guess:", class: 'form-label' %>
        <%= form.text_field :guess, class: 'form-control', placeholder: 'Make your next guess', autofocus: true %>
        <%= form.submit "Guess", class: 'btn btn-primary mt-2' %>
      <% end %>
    </div>
  </div>
<% end %>

<style>
  #word-field {
      padding: 20px 0;
  }
  #letter {
      font-size: 40px;
      height: 70px;
      text-align: center;
      vertical-align: middle;
  }
  #guess-form {
      margin: 30px 20px 0 20px
  }
  #winner, #game-over {
      text-align: center;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wordle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>